### ISSUE TITLE
Incorrect use of OpenAI error handling

### ISSUE THREAD

**Issue by sgarg26** [GustyCube/EasilyAI#13]
In `openai_service` and `grok_service`, we're using OpenAI errors like `openai.error.AuthenticationError`, when it's really `openai.AuthenticationError`. Examples can be found here: https://platform.openai.com/docs/guides/error-codes

**Comment by GustyCube** [comment]
Interesting. I can fix this, unless you want to

**Comment by sgarg26** [comment]
You can go for it, thanks!

**Comment by GustyCube** [comment]
Sounds good! Thanks!
