### ISSUE TITLE
Gemini Support

### ISSUE THREAD

**Issue by GustyCube** [GustyCube/EasilyAI#2]
We need to add support for Google's Gemini

We can follow the format of other integrations, I assume only a few pieces of it will need to change

**Comment by Thatoddone1** [comment]
Hi! I am working on this right now in a fork. Will share soon! 😁

**Comment by GustyCube** [comment]
Got it. Good luck :)

**Comment by GustyCube** [comment]
#9 is working on this.

**Comment by GustyCube** [comment]
This is done. I will add some more later on.
