### ISSUE TITLE
Grok Support

### ISSUE THREAD

**Issue by GustyCube** [GustyCube/EasilyAI#3]
We need to add support for X's Grok

We can follow the format of other integrations, I assume only a few pieces of it will need to change.

I believe there are both text and image reasoning models (see #4 for that)

**Comment by sgarg26** [comment]
Working on this! For now, I just have text completions, but will work on image generation also :)

**Comment by GustyCube** [comment]
@sgarg26 thats amazing! Thanks so much! Good luck!

**Comment by sgarg26** [comment]
Hello, just opened #10 for review at your convenience!

**Comment by GustyCube** [comment]
#10 has been approved. @sgarg26, do you plan on adding image support, or should we leave that to someone else?

**Comment by sgarg26** [comment]
Yes, currently working on that, should have it done soon.

**Comment by sgarg26** [comment]
Tasks:
- [ ] Add support for web based images
- [ ] Add support for local images
- [ ] Integrate with `pipeline`

**Comment by GustyCube** [comment]
@sgarg26 sorry, didn't see this. The latter is probably better for our scenario.

**Comment by sgarg26** [comment]
Yeah thought so too. I was busy over the last week, but I'll try and get something going

**Comment by GustyCube** [comment]
Sounds good!

**Comment by sgarg26** [comment]
Opened #14

**Comment by GustyCube** [comment]
Merged. Thank you so much for your help!

**Comment by sgarg26** [comment]
o7

**Comment by GustyCube** [comment]
🫡
