### ISSUE TITLE
Claude Support

### ISSUE THREAD

**Issue by GustyCube** [GustyCube/EasilyAI#8]
We need to add support for Claude

We can follow the format of other integrations, I assume only a few pieces of it will need to change

**Comment by AlexFierro9** [comment]
Can I Volunteer for this?

**Comment by GustyCube** [comment]
> Can I Volunteer for this?

@AlexFierro9 absolutely! Make sure to follow the conventions of the other services, and test it.

**Comment by GustyCube** [comment]
@AlexFierro9 do you still plan on working on this?

**Comment by AlexFierro9** [comment]
Yeah absolutely, give me 2-3 days for the same :)

**Comment by GustyCube** [comment]
Sounds good :)

**Comment by GustyCube** [comment]
@AlexFierro9 are you still working on this? If not, it's fine. We can find someone else.

**Comment by AlexFierro9** [comment]
@GustyCube Yeah no I'm still on it, unexpected delays in the way but getting there :')

**Comment by GustyCube** [comment]
#11 solves this.

**Comment by GustyCube** [comment]
We are going to work on expanding anthropic in the future. Thanks thus far!

**Comment by GustyCube** [comment]
We are going to work on expanding anthropic in the future. Thanks thus far!
